docker:
  image: yegor256/rultor-image:1.13.0
install: |
  pdd -f /dev/null
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/knowledge-base/version.rb
    git add lib/knowledge-base/version.rb
    git commit -m "version set to ${tag}"
merge:
  script: |-
    bundle exec rake